version: 0.2

phases:
  install:
    commands:
      - cd order-app
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - cd dist
      - aws s3 sync . "s3://${S3_BUCKET}"
