version: 0.2

phases:
  build:
    commands:
      - cd website
      - npm install
      - npm run build
      - cd dist
      - aws s3 sync . "s3://${S3_BUCKET}"
      - aws cloudfront create-invalidation --distribution-id ${CDN_ID} --paths /index.html /favicon.ico
